/**
 * Admin control plane for manifest sync, Storage discovery, ingestion queues, metadata updates,
 * listings, and short-lived source links. It is called by admin pages (and authenticated users
 * only for citation tokens), interacts with private kb-source-documents and canonical KB tables,
 * and begins or inspects the RAG ingestion pipeline without exposing service credentials.
 */
import {cors,json,requireUser} from "../_shared/core.ts";
const BUCKET="kb-source-documents",MANIFEST="manifests/HDD_Knowledge_Base_Source_Manifest.csv";
/** Parses conventional quoted CSV fields without requiring a third-party service. Malformed rows are reported by sync rather than silently deleted. */
function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field=""}else field+=c}if(field||row.length){row.push(field);rows.push(row)}return rows}
/** Normalizes manifest headings while preserving manual-only metadata through selective updates. */
function manifest(text:string){const [headers,...rows]=csvRows(text);if(!headers)throw new Error("Manifest is empty");return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h.trim().toLowerCase().replace(/\s+/g,"_"),values[i]?.trim()??""])))}
/** Handles one allow-listed action; admin authorization occurs before every mutation or listing. */
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const raw=await req.json();if(raw.action==="signed_source"){const {db}=await requireUser(req);let external="";try{external=atob(raw.source_token)}catch{return json({error:"Invalid source token"},400)}const {data}=await db.from("kb_documents").select("storage_bucket,storage_path").eq("document_id",external).eq("is_current",true).single();if(!data)return json({error:"Source unavailable"},404);const {data:signed,error}=await db.storage.from(data.storage_bucket).createSignedUrl(data.storage_path,60);if(error)throw error;return json({url:signed.signedUrl,expires_in:60})}const {db,user}=await requireUser(req,true);
if(raw.action==="list"){const {data,error}=await db.from("kb_documents").select("id,document_id,filename,jurisdiction_scope,project_code,authority_level,priority,storage_path,ingestion_status,chunk_count,parser_name,is_current,page_ranges_to_ingest").order("document_id");if(error)throw error;return json({documents:data})}
if(raw.action==="sync_manifest"){const {data:file,error:downloadError}=await db.storage.from(BUCKET).download(MANIFEST);if(downloadError)throw downloadError;const rows=manifest(await file.text());let inserted=0,updated=0,skipped=0;const errors:string[]=[];for(const row of rows){try{const id=row.document_id;if(!id||/manifest|archive|index/i.test(row.source_type||row.filename)){skipped++;continue}const {data:existing}=await db.from("kb_documents").select("id").eq("document_id",id).maybeSingle();const payload={document_id:id,filename:row.filename,title:row.title||row.filename,storage_path:row.storage_path||row.filename,jurisdiction:row.jurisdiction||null,jurisdiction_scope:row.jurisdiction_scope||"GENERAL",issuer:row.issuer||null,source_type:row.source_type||null,authority_level:row.authority_level||null,authority_rank:Number(row.authority_rank||20),project_specific:/true|yes|1/i.test(row.project_specific),project_code:row.project_code||null,status:row.status||null,priority:row.priority||null,rag_ingest:!/archive|index/i.test(row.source_type||"")&&/available/i.test(row.status||"AVAILABLE"),tags:(row.tags||"").split(/[;|]/).filter(Boolean)};const result=existing?await db.from("kb_documents").update(payload).eq("id",existing.id):await db.from("kb_documents").insert(payload);if(result.error)throw result.error;existing?updated++:inserted++}catch(e){errors.push(`${row.document_id||"unknown"}: ${e instanceof Error?e.message:"invalid row"}`)}}return json({inserted,updated,skipped,errors})}
if(raw.action==="scan_storage"){let inserted=0;const walk=async(prefix="")=>{const {data,error}=await db.storage.from(BUCKET).list(prefix,{limit:1000});if(error)throw error;for(const item of data??[]){const path=prefix?`${prefix}/${item.name}`:item.name;if(item.id&&/\.pdf$/i.test(item.name)){const {data:known}=await db.from("kb_documents").select("id").eq("storage_path",path).maybeSingle();if(!known){const code=`UNMAPPED-${crypto.randomUUID().slice(0,8)}`;const result=await db.from("kb_documents").insert({document_id:code,filename:item.name,title:item.name.replace(/\.pdf$/i,""),storage_path:path,ingestion_status:"NOT_INGESTED",rag_ingest:false,metadata:{discovered_by:"scan_storage"}});if(!result.error)inserted++}}else if(!item.id)await walk(path)}};await walk();return json({inserted,deleted:0})}
if(raw.action==="set_ranges"){if(typeof raw.page_ranges!=="string"||!/^(\s*\d+(-\d+)?\s*)(,\s*\d+(-\d+)?\s*)*$/.test(raw.page_ranges))return json({error:"Use ranges such as 5-15,120-140"},400);await db.from("kb_documents").update({page_ranges_to_ingest:raw.page_ranges,ingestion_status:"NOT_INGESTED"}).eq("id",raw.document_id);return json({updated:true})}
if(raw.action==="toggle_rag"){const {data}=await db.from("kb_documents").select("rag_ingest").eq("id",raw.document_id).single();await db.from("kb_documents").update({rag_ingest:!data?.rag_ingest}).eq("id",raw.document_id);return json({rag_ingest:!data?.rag_ingest})}
if(raw.action==="ingest"){const {data:doc}=await db.from("kb_documents").select("*").eq("id",raw.document_id).single();if(!doc)return json({error:"Document not found"},404);const {data:job,error}=await db.from("kb_ingestion_jobs").insert({document_id:doc.id,storage_path:doc.storage_path,requested_by:user.id,page_ranges:doc.page_ranges_to_ingest}).select().single();if(error)throw error;await db.from("kb_documents").update({ingestion_status:"QUEUED",ingestion_error:null}).eq("id",doc.id);const {data:signed,error:signError}=await db.storage.from(doc.storage_bucket).createSignedUrl(doc.storage_path,300);if(signError)throw signError;return json({job_id:job.id,pdf_url:signed.signedUrl,page_ranges:doc.page_ranges_to_ingest})}return json({error:"Unknown action"},400)}catch(error){console.error("kb-admin failed",error instanceof Error?error.message:"unknown");return json({error:error instanceof Error?error.message:"Request failed"},400)}});
