/**
 * Admin knowledge-base console. It invokes the admin-only kb-admin Edge Function to scan
 * private Storage, sync the manifest, queue ingestion, update ranges, and issue signed links.
 * It is the browser-operated entrance to parsing, chunking, Gemini embedding, and pgvector.
 */
import { useEffect,useState } from "react";import { supabase } from "../lib/supabase";import { PdfJsDocumentParser } from "../lib/documentParser";
type Doc={id:string;document_id:string;filename:string;jurisdiction_scope:string;project_code:string|null;authority_level:string;priority:string;storage_path:string;ingestion_status:string;chunk_count:number;parser_name:string|null;is_current:boolean;page_ranges_to_ingest:string|null};
/** Displays documents and safe actions. Server authorization failures are reported without exposing internals. */
export function KnowledgeBasePage(){const [docs,setDocs]=useState<Doc[]>([]);const [message,setMessage]=useState("");
  /** Runs one allow-listed admin action and refreshes rows after state-changing operations. */
  async function action(name:string,extra:Record<string,unknown>={}){setMessage("Working…");const {data,error}=await supabase.functions.invoke("kb-admin",{body:{action:name,...extra}});setMessage(error?error.message:JSON.stringify(data));if(!error&&name!=="list")await load();return {data,error};}
  /** Fetches the admin-safe document projection through the function rather than bypassing RLS. */
  async function load(){const {data,error}=await supabase.functions.invoke("kb-admin",{body:{action:"list"}});if(error)setMessage(error.message);else setDocs(data.documents)}useEffect(()=>{void load()},[]);
  return <section className="panel"><h1>Knowledge Base</h1><div className="controls"><button onClick={()=>action("sync_manifest")}>Sync Manifest</button><button onClick={()=>action("scan_storage")}>Scan Storage</button></div>{message&&<p className="warning">{message}</p>}<div className="table-wrap"><table><thead><tr><th>ID</th><th>File / scope</th><th>Authority</th><th>Status</th><th>Parser</th><th>Actions</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.document_id}</td><td>{d.filename}<br/><small>{d.jurisdiction_scope} · {d.storage_path}</small></td><td>{d.authority_level}</td><td>{d.ingestion_status} ({d.chunk_count})</td><td>{d.parser_name||"—"}</td><td><button onClick={async()=>{const result=await action("ingest",{document_id:d.id});if(result?.error||!result?.data)return;try{setMessage("Extracting PDF pages in this browser…");const parsed=await new PdfJsDocumentParser().parse(result.data.pdf_url,result.data.page_ranges);const ingest=await supabase.functions.invoke("ingest-document",{body:{job_id:result.data.job_id,pages:parsed.pages}});setMessage(ingest.error?ingest.error.message:JSON.stringify(ingest.data));await load()}catch(error){setMessage(error instanceof Error?error.message:"PDF parsing failed")}}}>{d.chunk_count?"Re-index":"Ingest"}</button> <button className="secondary" onClick={()=>{const ranges=prompt("Page ranges",d.page_ranges_to_ingest||"");if(ranges!==null)void action("set_ranges",{document_id:d.id,page_ranges:ranges})}}>Set ranges</button> <button className="secondary" onClick={()=>action("toggle_rag",{document_id:d.id})}>Disable RAG</button></td></tr>)}</tbody></table></div></section>}
