/**
 * Authenticated answer orchestrator: validates a field question, loads its project, classifies
 * applicability, creates a Gemini query embedding, invokes hybrid_search_kb, reranks evidence,
 * asks the existing Gemini generation model for strict JSON, and returns citation tokens.
 * It interacts with projects, kb_chunks/documents, pgvector, private Storage metadata and Gemini.
 */
import {cors,json,requireUser,embed,classify,gemini} from "../_shared/core.ts";
const MODEL="gemini-2.5-flash";
/** Handles one question. Any auth/provider/database failure becomes a non-secret HTTP error. */
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const {db}=await requireUser(req);const body=await req.json();const query=typeof body.query==="string"?body.query.trim():"";if(!query||query.length>2000)return json({error:"Query must contain 1–2,000 characters"},400);const projectCode=typeof body.project_code==="string"?body.project_code:undefined;const context=classify(query,projectCode);let project=null;if(projectCode){const result=await db.from("projects").select("*").eq("project_code",projectCode).eq("active",true).single();project=result.data;if(!project)return json({error:"Unknown project"},400)}const vector=await embed(query);const {data:evidence,error}=await db.rpc("hybrid_search_kb",{query_text:query,query_embedding:vector,project_code:projectCode??null,jurisdiction_scope:context.jurisdiction,include_udot:context.location_type==="UDOT_ROW",match_count:8,semantic_weight:1,keyword_weight:1});if(error)throw error;
// Recheck forbidden municipal scopes in code as defense in depth after the database filter.
const safe=(evidence??[]).filter((e:any)=>!(projectCode==="EP-22349"&&["PROVO","WEST_JORDAN"].includes(e.jurisdiction_scope))).slice(0,6);
const evidencePack=safe.map((e:any,i:number)=>`[S${i+1}] ${e.document_id}; ${e.title}; ${e.section_title??""}; pages ${e.page_start}-${e.page_end}; authority ${e.authority_rank}; scope ${e.jurisdiction_scope}\n${e.content}`).join("\n\n");
const schema={type:"object",properties:{answer:{type:"string"},what_to_say:{type:["string","null"]},authority_status:{type:"string",enum:["VERIFIED","PARTIAL","NOT_VERIFIED","NOT_APPLICABLE"]},confidence:{type:"string",enum:["HIGH","MEDIUM","LOW"]},warnings:{type:"array",items:{type:"string"}},source_indexes:{type:"array",items:{type:"integer"}}},required:["answer","what_to_say","authority_status","confidence","warnings","source_indexes"]};
const prompt=`You are a concise Utah HDD field assistant. Answer in ${body.language==="es"||context.language==="es"?"Spanish":"English"}. Use ONLY evidence below and cite material claims as [S#]. Never invent authority. Jurisdiction applicability precedes rank. Technical manuals, Blue Stakes, and LEAPS are not law. Generic PUE law never proves access to a particular private parcel. Project access needs accepted plans/easement/permit; otherwise PARTIAL or NOT_VERIFIED. Do not present translated legal language as official quotation. Project: ${JSON.stringify(project)}. Classification: ${JSON.stringify(context)}. Evidence:\n${evidencePack||"NO EVIDENCE"}`;
const generated=await gemini().models.generateContent({model:MODEL,contents:prompt,config:{responseMimeType:"application/json",responseJsonSchema:schema}});const parsed=JSON.parse(generated.text??"{}");const sources=await Promise.all((parsed.source_indexes??[]).filter((n:number)=>n>0&&n<=safe.length).map(async(n:number)=>{const e=safe[n-1];return {document_id:e.document_id,title:e.title,section:e.section_title,page_start:e.page_start,page_end:e.page_end,authority_rank:e.authority_rank,jurisdiction_scope:e.jurisdiction_scope,source_token:btoa(e.document_id)}}));return json({...parsed,sources,classification:context});}catch(error){console.error("ask-supervisor failed",error instanceof Error?error.message:"unknown");return json({error:error instanceof Error?error.message:"Request failed"},400)}});
